version: '2.3'

services:
    angular-cli:
        build:
            context: docker/ng
            args:
                NODE_VERSION: ${NODE_VERSION}
                ANGULAR_CLI_VERSION: ${ANGULAR_CLI_VERSION}
        ports:
            - ${ANGULAR_CLI_PORT}:4200
        volumes:
            - ${ANGULAR_APP_PATH}/angular:/tmp/angular:z
            - ./angular/node_modules:/tmp/angular/node_modules:z
    native-cli:
        build:
            context: docker/tns
            args:
                NODE_VERSION: ${NODE_VERSION}
                NATIVESCRIPT_CLI_VERSION: ${NATIVESCRIPT_CLI_VERSION}
        privileged: true
        volumes:
            - ${ANGULAR_APP_PATH}/angular/nativescript:/tmp/nativescript:z
    app:
        build: docker/build
        image: ${DOCKER_REGISTRY_PATH}:${DOCKER_REGISTRY_PORT}/angular-app:${APPLICATION_VERSION:-dev}
        restart: always
        ports:
            - ${ANGULAR_APP_PORT}:80
        volumes:
            - ${ANGULAR_APP_PATH}/angular/dist:/var/www/angular
            - ./angular/serverlogs:/var/log/nginx